# Keywords for DEI, NGO and other waste fraud detection filters
DEI_KEYWORDS = [
    "DEI",
    "diversity",
    "equity",
    "inclusion",
    "gender",
    "civil rights",
    "non-binary",
    "environmental justice",
    "sustainability",
    "resilience",
    "empowerment",
    "inclusive",
    "justice",
    "social justice",
    "racial justice",
    "gender justice",
    "female",
    "indigenous",
    "LGBT",
    "literacy",
    "education",
    "poverty",
    "humanitarian",
]

NGO_KEYWORDS = [
    "environmental justice",
    "sustainability",
    "green",
    "climate",
    "NGO",
    "non-profit",
    "charity",
    "shell company",
    "foreign aid",
    "low-income",
    "disadvantaged",
    "non government organization",
    "foundation",
    "institution",
    "institute",
    "consulting",
    "support",
    "training",
    "consulting",
    "capacity building",
    "technical assistance",
    "management",
    "operational costs",
    "strategic planning",
    "miscellaneous expenses",
    "innovation",
    "empowerment",
    "community development",
    "outreach",
    "engagement",
    "awareness",
    "partnership",
    "collaboration",
    "initiatives",
    "pass-through",
    "subcontract",
    "emergency funding",
    "discretionary",
    "unallocated",
    "reimbursement",
    "pilot project",
    "startup costs",
    "overhead",
    "third-party",
    "newly established",
    "emerging organization",
    "grassroots",
    "rapid deployment",
    "seed funding",
    "non-competitive",
    "sole source",
    "humanitarian aid",
    "foreign assistance",
    "advocacy",
]

WASTE_KEYWORDS = [
    "support",
    "assistance",
    "aid",
    "help",
    "backing",
    "resources",
    "provision",
    "maintenance",
    "sustainment",
    "upkeep",
    "clerical",
    "administrative",
    "office support",
    "paperwork",
    "filing",
    "record keeping",
    "data entry",
    "secretarial",
    "coordination",
    "logistics",
    "mail",
    "mailing",
    "distribution",
    "correspondence",
    "delivery",
    "shipping",
    "postage",
    "communication",
    "messaging",
    "dissemination",
    "consult",
    "consulting",
    "advisory",
    "advice",
    "guidance",
    "counsel",
    "expertise",
    "input",
    "recommendations",
    "consultancy",
    "training",
    "workshop",
    "seminar",
    "facilitate",
    "facilitation",
    "education",
    "instruction",
    "orientation",
    "development",
    "capacity",
    "meeting",
    "conference",
    "travel",
    "event",
    "retreat",
    "promotion",
    "publicity",
    "materials",
    "supplies",
    "miscellaneous",
]

keywords = {
    "main": list(set(DEI_KEYWORDS + NGO_KEYWORDS + WASTE_KEYWORDS)),
    "dei": DEI_KEYWORDS,
    "ngo": NGO_KEYWORDS,
    "waste": WASTE_KEYWORDS,
}
